Repository hmcts/ccfr-fees-register-app, pull requests merged in 2018-11, with the labels that each got.

#178 Point to SIDAM
  infrastructure/aat.tfvars
Labels: ns:fees-register-api-pr-178

#179 fixed CVE related issues and upgraded libs
  api/build.gradle
  api/src/main/resources/application.properties
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-register-api-pr-179

#180 bump version
  version.txt
Labels: ns:fees-register-api-pr-180

#184 CVE-2018-10237 fix
  dependency-check-suppressions.xml
  model/build.gradle
Labels: ns:fees-register-api-pr-184

#185 removed access attribute from version prop
  api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/FeeVersionDto.java
Labels: ns:fees-register-api-pr-185
