Repository hmcts/ccfr-fees-register-app, pull requests merged in 2019-07, with the labels that each got.

#234 Ithc
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  version.txt
Labels: ns:fees-register-api-pr-234

#233 PAY-1824 Duplicate fee codes issue fixed
  api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/FeeVersionStatusDto.java
  api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/FeeController.java
  api/src/main/resources/application.properties
  api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/FeeControllerTest.java
  api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeSearchServiceTest.java
  infrastructure/main.tf
  model/src/main/java/uk/gov/hmcts/fees2/register/data/dto/SearchFeeVersionDto.java
  model/src/main/java/uk/gov/hmcts/fees2/register/data/model/FeeVersionStatus.java
  model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeSearchServiceImpl.java
Labels: ns:fees-register-api-pr-233

#236 Updated spring boot version
  build.gradle
  client/build.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-register-api-pr-236
