Repository hmcts/ccfr-fees-register-app, pull requests merged in 2020-06, with the labels that each got.

#295 PAY-2874-chart-changes
  charts/fees-register-api/Chart.yaml
  charts/fees-register-api/values.yaml
Labels: ns:fees-pay, rel:fees-register-api-pr-295

#298 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-298

#304 PAY-3398 : Nightly Build Issue Fix
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-304
