Repository hmcts/ccfr-fees-register-app, pull requests merged in 2020-10, with the labels that each got.

#318 Nightly build issue fix
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-318

#317 PAY-3692- Azure rm version upgrade changes
  dependency-check-suppressions.xml
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-317

#319 PAY-3691 : Vunerabilities raise because of uk.gov.hmcts.java version …
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-319
