Repository hmcts/ccfr-fees-register-app, pull requests merged in 2021-02, with the labels that each got.

#338 Modified Functional Tests
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/CategoriesIntegrationForCMCTest.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/dsl/FeesRegisterTestDsl.java
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-338

#339 Pay-4085: Nightly Build issue Fix
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-339

#341 Pay-4115-Nightly Build issue fix
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-341
