Repository hmcts/ccfr-fees-register-app, pull requests merged in 2021-06, with the labels that each got.

#366 upgrade spring boot version for CVE-2021-22118
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-366

#379 Pay 4106.1
  api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/loader/request/LoaderRelationalFeeDto.java
  api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/request/RelationalFeeDto.java
  api/src/main/java/uk/gov/hmcts/fees2/register/api/controllers/mapper/FeeLoaderJsonMapper.java
  api/src/main/java/uk/gov/hmcts/fees2/register/util/FeeFactory.java
  api/src/main/java/uk/gov/hmcts/fees2/register/util/FeeLoader.java
  api/src/main/resources/feeLoader.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-379

#364 PAY:4612:sync demo,ithc and perftest with master branch
  Jenkinsfile_CNP
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-364
