Repository hmcts/ccfr-fees-register-app, pull requests merged in 2021-01, with the labels that each got.

#330 Ccfr fees register app nightly build
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-330

#327 PAY-3831 : helm chart upgrade changes and spring boot 2.3.0 upgrade
  api-contract/build.gradle
  api/build.gradle
  api/src/main/java/uk/gov/hmcts/fees/register/api/configuration/SpringSecurityConfiguration.java
  api/src/main/resources/application-local.properties
  api/src/main/resources/application.properties
  build.gradle
  charts/fees-register-api/Chart.yaml
  charts/fees-register-api/requirements.yaml
  charts/fees-register-api/values.yaml
  client/build.gradle
  dependency-check-suppressions.xml
  model/build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-327

#332 PAY-3917 : Removed the OLD DB instance mapping from main.tf
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-332

#321 adding divorce provider pact test verification
  Jenkinsfile_CNP
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-321

#329 DTSPO-266 Enable self service read only access
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-329

#336 PAY-3962 Fee reg CVE fix
  api-contract/build.gradle
  api/build.gradle
  build.gradle
  client/build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
  model/build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-336
