Repository hmcts/ccfr-fees-register-app, pull requests merged in 2022-09, with the labels that each got.

#481 Cve Fix- CVE-2022-25857
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-481

#482 Cve suppressed - CVE-2022-38749, CVE-2022-38750, CVE-2022-38751
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-482

#484 refactor tests
  .gitignore
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIToRetrieveTheCorrectFeeTest.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/IntegrationTestBase.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/UpdateFeeTest.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/UserBootstrap.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/idam/IdamApi.java
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/idam/IdamService.java
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-484

#485 update date in suppression file
  .gitignore
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-485

#487 update suppression file
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-487
