Repository hmcts/ccfr-fees-register-app, pull requests merged in 2022-11, with the labels that each got.

#492 upgrade tomcat embed version
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-492

#493 upgrade snake yaml
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-493

#496 PAY-5639 Fixed Sonar issues
  api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/LookUpFeeBorderTestCasesTest.java
  api/src/test/java/uk/gov/hmcts/fees2/register/api/controllers/LookupFeeBorderTestCases.java
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-496

#497 suppressing postrges cve, no fix available
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-497
