Repository hmcts/ccfr-fees-register-app, pull requests merged in 2023-11, with the labels that each got.

#555 Pay 6575 flexible db
  charts/fees-register-api/Chart.yaml
  charts/fees-register-api/values.yaml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-555

#556 PAY-6571: Temp disable pact test
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-556

#557 PAY-6575: Add missing product name
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-api-pr-557

#558 PAY-6683 SDP user setup
  infrastructure/sdp.tf
Labels: ns:fees-pay, prd:fees-register, add-or-update, rel:fees-register-api-pr-558

#559 PAY-6701 Force access to tables
  charts/fees-register-api/Chart.yaml
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, destroy, rel:fees-register-api-pr-559

#560 PAY-6702 SDP access
  infrastructure/sdp.tf
Labels: ns:fees-pay, prd:fees-register, destroy, rel:fees-register-api-pr-560
