Repository hmcts/ccfr-fees-register-app, pull requests merged in 2023-06, with the labels that each got.

#525 surpression for spring
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-525

#526 fix cves
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-526

#527 CVE-2023-2976 and CVE-2022-1471 Suppression.
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-527
