Repository hmcts/ccfr-fees-register-app, pull requests merged in 2023-02, with the labels that each got.

#506 cve fix
  build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-506

#508 suppressing cve, no fix available
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-508

#509 variable ilbIp no longer required
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-api-pr-509
