Repository hmcts/ccfr-fees-register-app, pull requests merged in 2023-12, with the labels that each got.

#563 PAY-6720: Update to suppressions, sdp fix and secrets correction.
  dependency-check-suppressions.xml
  infrastructure/main.tf
  infrastructure/sdp.tf
Labels: ns:fees-pay, prd:fees-register, destroy, rel:fees-register-api-pr-563

#564 PAY-6746 logback cve resolution
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-564

#565 PAY-6659 Decommission v11 database
  charts/fees-register-api/Chart.yaml
  charts/fees-register-api/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:fees-register, destroy, rel:fees-register-api-pr-565

#566 PAY-6756 owasp upgrade
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-566
