Repository hmcts/ccfr-fees-register-app, pull requests merged in 2023-01, with the labels that each got.

#500 Test pact verification changes
  Jenkinsfile_CNP
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-500

#502 cve fix
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-502

#504 updated deprecated after to afterAlways
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/fees-register-api/Chart.yaml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-504

#503 Terraform version upgraded to 1.3.7
  infrastructure/.terraform-version
  infrastructure/versions.tf
Labels: ns:fees-pay, prd:fees-register, no-changes, rel:fees-register-api-pr-503
