Repository hmcts/ccfr-fees-register-app, pull requests merged in 2024-11, with the labels that each got.

#596 PAY-7456
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-596

#597 PAY-7456
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-597

#602 CME-65: Java 21
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  jitpack.yml
Labels: ns:fees-pay, prd:fees-register, enable_keep_helm, rel:fees-register-api-pr-602
