Repository hmcts/ccfr-fees-register-app, pull requests merged in 2024-06, with the labels that each got.

#580 PAY-7141: Address Medium Vulnerabilities
  build.gradle
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, enable_keep_helm, rel:fees-register-api-pr-580

#581 PAY-7141: Jitpack update
  build.gradle
  jitpack.yml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-581

#585 PAY-6863 re-enable pact verification
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-585

#586 PAY-6863 changes to fix pact verification
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-586

#587 Revert "PAY-6863 changes to fix pact verification"
  build.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-587
