Repository hmcts/ccfr-fees-register-app, pull requests merged in 2024-02, with the labels that each got.

#567 PAY-6872 CVE 2023-34042
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-567

#568 PAY-6882
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-568

#569 PAY-6909: Force DB user to be added to readonly group
  charts/fees-register-api/Chart.yaml
  infrastructure/main.tf
Labels: destroy
