Repository hmcts/ccfr-fees-register-app, pull requests merged in 2025-01, with the labels that each got.

#610 PAY-7497: Problems in demo env and others that block testing, AAT and…
  api-contract/src/main/java/uk/gov/hmcts/fees2/register/api/contract/FeeVersionDto.java
  api/src/main/java/uk/gov/hmcts/fees/register/api/configuration/SpringSecurityConfiguration.java
Labels: ns:fees-pay, prd:fees-register, enable_keep_helm, rel:fees-register-api-pr-610

#612 PAY-7497: Problems in demo env and others that block testing, AAT and…
  Jenkinsfile_CNP
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-612

#613 CME-322: Update azurerm
  infrastructure/state.tf
Labels: ns:fees-pay, prd:fees-register, aat/add-or-update, prod/add-or-update
