Repository hmcts/ccfr-fees-register-app, pull requests merged in 2025-07, with the labels that each got.

#637 https://tools.hmcts.net/jira/browse/PAY-7980
  audit.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-637

#638 PAY-7984 commons-lang3 cve
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-638

#639 PAY-7940 tomcat cve
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-639
