Repository hmcts/ccfr-fees-register-app, pull requests merged in 2025-04, with the labels that each got.

#621 PAY-7704 to fix functional tests
  api/src/functionalTest/java/uk/gov/hmcts/fees/register/functional/Fees2APIFeeControllerTest.java
  api/src/main/resources/feeLoader.json
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-621

#622 Testing
  README.md
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-622

#624 PAY-7727: Apply descending order to fee versions
  api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeSearchServiceTest.java
  api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeServiceTest.java
  api/src/test/java/uk/gov/hmcts/fees2/register/api/service/FeeVersionServiceTest.java
  build.gradle
  model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeSearchServiceImpl.java
  model/src/main/java/uk/gov/hmcts/fees2/register/data/service/impl/FeeServiceImpl.java
Labels: ns:fees-pay, prd:fees-register, enable_keep_helm, rel:fees-register-api-pr-624

#626 PAY-7516 enable pact
  Jenkinsfile_CNP
Labels: ns:fees-pay, prd:fees-register, rel:fees-register-api-pr-626

#627 PAY-7766 removal of the azure.extension plpgsql
  infrastructure/main.tf
Labels: ns:fees-pay, prd:fees-register, aat/destroy, prod/add-or-update, rel:fees-register-api-pr-627
